//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_attributes_values
    {
        public string id { get; set; }
        public string attribute_value { get; set; }
        public string config_attributes_id { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        public virtual config_attributes config_attributes { get; set; }
    }
}
