//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_attributes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public config_attributes()
        {
            this.config_attributes_values = new HashSet<config_attributes_values>();
        }
    
        public string id { get; set; }
        public string attribute_name { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<config_attributes_values> config_attributes_values { get; set; }
    }
}
