//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories.MySql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class monitoringEntities : DbContext
    {
        public monitoringEntities()
            : base("name=monitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<config_attributes> config_attributes { get; set; }
        public virtual DbSet<config_attributes_values> config_attributes_values { get; set; }
        public virtual DbSet<monitoring_services> monitoring_services { get; set; }
        public virtual DbSet<monitoring_services_jobs> monitoring_services_jobs { get; set; }
        public virtual DbSet<monitoring_services_responses> monitoring_services_responses { get; set; }
    }
}
