//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitoring_services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public monitoring_services()
        {
            this.monitoring_services_jobs = new HashSet<monitoring_services_jobs>();
        }
    
        public string id { get; set; }
        public string description { get; set; }
        public string class_name { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime updated_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<monitoring_services_jobs> monitoring_services_jobs { get; set; }
    }
}
